#!/usr/bin/env bash
# Function to display information about a subdomain

display_info() {
    local domain=$1
    local subdomain=$2
    local record_info=$(dig +short -t A ${subdomain}.${domain})

    echo "The subdomain ${subdomain} is a A record and points to ${record_info}"
}

# Check if a subdomain is provided
if [ -z "$2" ]; then
    # Display information for default subdomains
    for subdomain in www lb-01 web-01 web-02; do
        display_info $1 $subdomain
    done
else
    # Display information for the provided subdomain
    display_info $1 $2
fi