#!/usr/bin/env bash

# Check if at least 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit 1
fi

# Assigning parameters to variables for better readability
PATH_TO_FILE=$1
SERVER_IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# SCP Command to transfer the file to the server's user home directory
# StrictHostKeyChecking=no disables the prompt that asks for verification of the host key.
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$SERVER_IP:~/"
