#!/usr/bin/env bash
# Install Nginx web server
sudo su

# Install the Nginx web server software.
apt-get update -y
apt-get install -y nginx

# Write "Hello World!" to the index.html file.
echo "Hello World!" > /var/www/html/index.html

# Restart the Nginx service to apply the new configuration.
service nginx restart
