#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect following requirements
apt-get update -y
apt-get install -y nginx

# Write "Hello World!" to the index.html file.
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx server
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://google.com/;
    }
}
EOF

# Restart the Nginx service to apply the new configuration.
service nginx restart
