#!/usr/bin/env bash
#configure a custom 404 page

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow HTTP traffic through the firewall
ufw allow 'Nginx HTTP'

# Set proper permissions for the web root
chmod -R 755 /var/www

# Create a simple index.html page
echo 'Hello World' > /var/www/html/index.html

# Define the new Nginx server configuration
new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }

        # location /redirect_me {
        #    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        # }

        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Apply the new Nginx configuration
echo "$new_config" > /etc/nginx/sites-available/default

# Start or restart Nginx to apply changes
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
