#!/usr/bin/env bash
# Check if nginx is installed, if not install it
# Change the listen directive to listen on port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
