#!/bin/bash

# Use ssh with single-character flags to connect to the server
# -i specifies the identity file (private key)
# The username and server IP address are specified directly in the command
ssh -i ~/.ssh/school ubuntu@100.26.136.175
